name: Deploy Application

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Build Spring Boot application
      run: mvn clean package

    - name: Build React application
      run: |
        cd frontend
        npm install
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          backend/target/*.jar
          frontend/build

    - name: Deploy to Azure VM
      env:
        AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
        AZURE_VM_USER: ${{ secrets.AZURE_VM_USER }}
        AZURE_VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
      run: |
        scp -o StrictHostKeyChecking=no -r backend/target/*.jar frontend/build $AZURE_VM_USER@$AZURE_VM_IP:/path/to/deploy
        ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP << 'EOF'
          sudo systemctl restart my-spring-boot-app
          sudo cp -r /path/to/deploy/frontend/build /path/to/nginx/html
          sudo systemctl restart nginx
        EOF
